---
# File: main.yml
# Type: task
# Part: Redis

- include: install-trusty.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int <= 14
- include: install-xenial.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int >= 16
